### ISSUE TITLE
Any samples?

### ISSUE THREAD

**Issue by wizardk** [keonlee9420/VAENAR-TTS#3]
@keonlee9420 Hi, are there any samples to show?

**Comment by keonlee9420** [comment]
Hi @wizardk , so sorry for the too late response, I just found that I missed this issue. Here is [a link](https://drive.google.com/drive/u/3/folders/1LER6b22ghty6mnw48jL0Ryc58k6ryiK_) where I shared a single demo file. If you need more, I'd like to recommend you to run the pre-trained model following README.md.

**Comment by wizardk** [comment]
Thanks.
